### ISSUE TITLE
Support for the `is` attribute for customized built-in elements

### ISSUE THREAD

**Issue by troyvassalotti** [jdvivar/eleventy-plugin-add-web-component-definitions#24]
Web components can also be customized built-in elements using the [`is` attribute](https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_custom_elements#customized_built-in_elements) as long as the web component specifically extends that element. The plugin adds web component definitions based on the tag name but doesn't check for built-in elements using `is`.

I've actually been messing around with this locally and _think_ I have it working, but didn't want to open a pull request before discussing the feature and checking for contribution requirements.

**Comment by jdvivar** [comment]
In a production environment, this part of the standard is avoided since Safari (and therefore all browsers on iOS based devices) does not support extending native elements. That's why you won't see any UI library based on Web Components with native elements extended.

See the notes on browser compatibility here
https://developer.mozilla.org/en-US/docs/Web/API/CustomElementRegistry/define#browser_compatibility

**Comment by jdvivar** [comment]
Hey @troyvassalotti, knowing the above, are you still interested in support for the `is` attribute?

**Comment by troyvassalotti** [comment]
Considering the lack of Safari support, I don't think it's necessary to add to the plugin unless there are more requests for its inclusion. I'd be interested if/when Safari allows it though. Feel free to close the issue for the time being if that is ideal.
